### ISSUE TITLE
Confusion with the steps to follow in the Models section.

### ISSUE THREAD

**Issue by CallMeMael** [WGLab/PhenoGPT2#1]
Hello.

I was wondering what it means when it says:

"Download the updated fine-tuning in the release section on GitHub (Latest version: v1.0.0)"

I’m not sure if it’s referring to the LLaMa models or other models. In case it refers to the LLaMa model, I can't find the GitHub repository.

I hope you can help me.

**Comment by quannguyenminh103** [comment]
Hi,
Thank you so much for checking out our model. Unfortunately, our PhenoGPT2 is still being refined and not finalized yet. Please use the first version of PhenoGPT: https://github.com/WGLab/PhenoGPT.
PhenoGPT2 is coming soon! Keep an eye out in the next few months for the release.

**Comment by Fealo** [comment]
To add on to this - have the new fine tunes been released ?

**Comment by quannguyenminh103** [comment]
Hi Fealo,

Thanks for be interested in our model. We are currently developing the new models based on Llama 3.3 version. We will release it in the near future!

**Comment by harshmeet30** [comment]
Now released ?
